### ISSUE TITLE
Download RTF on iOS < 13

### ISSUE THREAD

**Issue by flachware** [zotero/bib-web#151]
The _Download RTF_ button opens the RTF source code in the browser on iOS. Would it be possible to download the file similar to the RIS format?

![img_1074](https://user-images.githubusercontent.com/419747/37836968-423f9d50-2eb4-11e8-8a52-a1a969677377.PNG)

**Comment by tnajdek** [comment]
It behaves correctly on updated devices and I don't think we can do much about it for iOS < 13.
