### ISSUE TITLE
Consider reordering of citations

### ISSUE THREAD

**Issue by flachware** [zotero/bib-web#167]
@dstillman I know we discussed this already, but there are quite some CSL styles that do not use alphabetical order but the order of appearance – I do think we should give the user a way to reorder the citations in the bibliography (e.g. via a sortable component), otherwise working with these styles would just be less fun.

**Comment by claudia-lat** [comment]
Any happy news on this? It would be great if the order of the appearance was the one of insertion.  Each user could insert references from the latest to the oldest (or viceversa).  Just to have a temporal ordered list :)

**Comment by dstillman** [comment]
@claudia-lat: No updates, but to be clear, if we did this, it would be limited to numeric/footnote styles. Other styles would always be sorted by the order defined in the style (e.g., alphabetical). It's possible for styles to sort by publication date, but I'm not sure if any existing styles do.

**Comment by tnajdek** [comment]
Done, will be part of 2.1.0 release.
