### ISSUE TITLE
Remove button does not always work

### ISSUE THREAD

**Issue by flachware** [zotero/bib-web#230]
Especially when I want to delete more items consecutively I have to click twice on the remove button to delete an item.

![screen shot 2018-05-16 at 09 28 23](https://user-images.githubusercontent.com/419747/40102741-9736f5fe-58eb-11e8-9a1a-5825e341f4eb.png)

**Comment by tnajdek** [comment]
Can't seem to reproduce, any hints?

![bib-web-230 mov](https://user-images.githubusercontent.com/214628/40181565-4b09f87e-59e1-11e8-9e80-df540ebf7401.gif)

**Comment by flachware** [comment]
It only happens in Chrome for me. My suspicion is that it happens because I have both the latest Chrome version and the beta version installed. So if this only happens on my machine once again and nobody can reproduce it on Chrome 66, it does not exist.

**Comment by tnajdek** [comment]
I couldn't reproduce on Chrome 66.0.3359.139

**Comment by flachware** [comment]
OK, let’s say it’s just me (on Chrome 66.0.3359.181).
