### ISSUE TITLE
Set bibliography locale based on browser locale

### ISSUE THREAD

**Issue by dstillman** [zotero/bib-web#240]
https://forums.zotero.org/discussion/comment/310417/#Comment_310417

Can we do that?

I think the Language tag of items will currently override on a per-item basis, but this would be for the bibliography as a whole.

**Comment by tnajdek** [comment]
(https://forums.zotero.org/discussion/78941/multilanguage-support-for-zbib)

If I understand the issue correctly, I believe this [already works like that](https://github.com/zotero/bib-web/blob/master/src/js/utils.jsx#L30) - just tested in Firefox and Chrome by setting language to German (de-de):

![Screenshot 2019-09-05 at 12 28 54](https://user-images.githubusercontent.com/214628/64338161-ee55d980-cfd8-11e9-8c7a-98ea903e1a91.png)
