### ISSUE TITLE
Error loading zbib.org on iOS 9.2.1

### ISSUE THREAD

**Issue by flachware** [zotero/bib-web#245]
@tnajdek when I try to load zbib.org on an iPad with iOS 9.2.1 I get the following error (page stays blank):

![screen shot 2018-07-20 at 12 29 14](https://user-images.githubusercontent.com/419747/42997938-c1d0ba92-8c18-11e8-94cf-cf634bdd4ff9.png)

**Comment by tnajdek** [comment]
iOS 9.x compatibility was indeed broken and has been fixed somewhere between e75af574 and 2d52bd5c (also probably also affected by #237 which was fixed in 9e2594b0)
