### ISSUE TITLE
Support for importing to ZoteroBib

### ISSUE THREAD

**Issue by tnajdek** [zotero/bib-web#246]
A new feature that would allow external sites offer export to ZoteroBib.

- [x] A new "endpoint", for example `/import` that takes URL as only argument, e.g `/import?url=https://example.com/some-id`. This interface would use translation server to process URL provided and would display item(s) that would be imported. At this stage the end user can choose to add to his existing bibliography, replace it, or discard the import.
- [x] A new section in FAQ that would outline how this works and what URL to provide

**Comment by dstillman** [comment]
Rather than `url`, I assume this can just be `q` and be equivalent to the input field (like we're doing on https://www.zotero.org/save).

**Comment by dstillman** [comment]
For sites that already have data, we could also accept URL-encoded data in a `data` parameter, in any import format we support, and pass that to translation-server's `/import` endpoint.
