### ISSUE TITLE
What service is used for title search?

### ISSUE THREAD

**Issue by dhimmel** [zotero/bib-web#257]
https://zbib.org/ is super cool. I'm interested in performing the metadata lookup for a URL/identifier/title programmatically. My understanding is that the URL and identifier lookups use translation-server.

However, what is used when searching a title? For example, my browser creates the following API call when searching `systematic drug repurposing himmelstein`:

```shell
curl 'https://t0guvf0w17.execute-api.us-east-1.amazonaws.com/Prod/search' -H 'Origin: https://zbib.org' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36' -H 'DNT: 1' -H 'Content-Type: text/plain' --data-binary 'systematic drug repurposing himmelstein' --compressed
```

Is `https://t0guvf0w17.execute-api.us-east-1.amazonaws.com/Prod/search` a translation-server instance? When I run the following on a different translation-server instance, I get `No identifiers found`:

```shell
curl 'https://translate.manubot.org/search' -H 'DNT: 1' -H 'Content-Type: text/plain' --data-binary 'systematic drug repurposing himmelstein' --compressed
```

**Comment by dstillman** [comment]
Sorry, title search isn't public, and it relies on data we're not able to make public. Crossref has public APIs that you could look into using.

(That endpoint is also a private API and shouldn't be used externally.)
