### ISSUE TITLE
Citation creation through HTTP GET parameter

### ISSUE THREAD

**Issue by Abbe98** [zotero/bib-web#259]
It would be very neat if one could integrate ZoteroBib citation generation by linking to the site with a given get parameter:

`https://zbib.org?source=<url, isbn, doi, etc>`

The result of visiting such a link should be equal to the result of manually pasting a value into the search box and clicking "Cite".

**Comment by dstillman** [comment]
You can — we just haven't documented it yet.

Use `q=`. Can also be a link to an export format (RIS, BibTeX), which makes it easy to integrate with a library catalog.
