### ISSUE TITLE
Allow short DOIs

### ISSUE THREAD

**Issue by dstillman** [zotero/bib-web#51]
In the form 10/aabbe — see http://shortdoi.org/.

I think `^10(?:\.[0-9]{4,})?\/[^\s]*[^\s\.,]$` would work — as in, just make the `.<number>` between the `10` and the `/` optional.

**Comment by bwiernik** [comment]
(shortDOI links resolve correctly through http://doi.org/ now)

**Comment by dstillman** [comment]
Fixed after updating to the latest translators, which include the new DOI Content Negotiation translator.
